---
name: PostHog Error Debugging

on:
    workflow_dispatch:
        inputs:
            query_type:
                description: Query type
                required: true
                type: choice
                options:
                    - event-query
                    - event-id
                default: event-query
            posthog_query:
                description: PostHog query (event name or event ID)
                required: true
                default: $exception
            repo_list:
                description: Comma-separated list of repos to analyze (owner/repo)
                required: true
                default: OpenHands/OpenHands,All-Hands-AI/infra
            issue_repo:
                description: Repository to create issues in (owner/repo)
                required: true
                default: All-Hands-AI/infra
            issue_parent:
                description: Parent issue URL (optional)
                required: false
            issue_prefix:
                description: Prefix for issue titles
                required: false
                default: 'PostHog Error: '
            max_events:
                description: Maximum number of events to fetch
                required: false
                default: '5'
            llm_model:
                description: LLM model to use
                required: false
                default: anthropic/claude-sonnet-4-5-20250929

permissions:
    contents: read
    issues: write

jobs:
    debug-posthog-errors:
        runs-on: ubuntu-latest
        timeout-minutes: 60

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.13'

            - name: Download debugging script
              run: |
                  mkdir -p posthog_debug_tools
                  cd posthog_debug_tools

                  # Download the debugging script and template
                  curl -O https://raw.githubusercontent.com/OpenHands/software-agent-sdk/main/examples/03_github_workflows/05_posthog_debugging/posthog_debugging.py
                  curl -O https://raw.githubusercontent.com/OpenHands/software-agent-sdk/main/examples/03_github_workflows/05_posthog_debugging/debug_prompt.jinja

                  chmod +x posthog_debugging.py

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install openhands-sdk requests jinja2

            - name: Run PostHog debugging
              env:
                  POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
                  POSTHOG_PROJECT_ID: ${{ secrets.POSTHOG_PROJECT_ID }}
                  POSTHOG_HOST: ${{ secrets.POSTHOG_HOST }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
                  LLM_BASE_URL: ${{ secrets.LLM_BASE_URL }}
                  LLM_MODEL: ${{ inputs.llm_model }}
              run: |
                  cd posthog_debug_tools
                  python posthog_debugging.py \
                    --query-type "${{ inputs.query_type }}" \
                    --query "${{ inputs.posthog_query }}" \
                    --repos "${{ inputs.repo_list }}" \
                    --issue-repo "${{ inputs.issue_repo }}" \
                    ${{ inputs.issue_parent && format('--issue-parent "{0}"', inputs.issue_parent) || '' }} \
                    --issue-prefix "${{ inputs.issue_prefix }}" \
                    --working-dir ./workspace

            - name: Upload debugging artifacts
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: posthog-debug-results
                  path: posthog_debug_tools/workspace/
                  retention-days: 7
